# logging
logging:
  level: INFO
  loggers:
    com.tapifolti.videorentalstore: DEBUG
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: videorentalstore.log
      archivedLogFilenamePattern: videorentalstore-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 5MB

# renting conditions
rentConditions:
  premiumInitialPrice: 40
  premiumDayPrice: 40
  premiumInitialDays: 1
  premiumBonusPoint: 2
  regularInitialPrice: 30
  regularDayPrice: 30
  regularInitialDays: 3
  regularBonusPoint: 1
  oldInitialPrice: 30
  oldDayPrice: 30
  oldInitialDays: 5
  oldBonusPoint: 1