logging:
  level: INFO
  loggers:
    com.tapifolti.videorentalstore: DEBUG
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: videorentalstore.log
      archivedLogFilenamePattern: videorentalstore-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 5MB